### ISSUE TITLE
Any different with BackgroundMattingV2?

### ISSUE THREAD

**Issue by yfq512** [PeterL1n/RobustVideoMatting#1]

**Comment by PeterL1n** [comment]
* Does not require a pre-captured background.
* Process videos with temporal memory instead of processing every frame as independent images.
* Faster
* Lighter
* No longer use patch-based refinement, architecture should be supported by all inference framework.
* Trained on more data, more robust.

**Comment by pango99** [comment]
Only consider quality, which is better?

**Comment by PeterL1n** [comment]
If you are able to capture a perfect background as supplement, BGMv2 is still better as shown in the metrics.

If you are more advanced, you can also modify RVM to supply a background, it should do better than BGMv2 because of the recurrent nature.

**Comment by pango99** [comment]
> 
> If you are more advanced, you can also modify RVM to supply a background, it should do better than BGMv2 because of the recurrent nature.

How to modify RVM to supply background ?

**Comment by PeterL1n** [comment]
@pango99 You will have to investigate the model architecture and training strategy yourself.
