### ISSUE TITLE
Not Issue 👉 Few questions 

### ISSUE THREAD

**Issue by AlonDan** [PeterL1n/RobustVideoMatting#10]
First of all thank you for working on this project! it looks much stronger than the BMV2 !
---
**1**.  Will it work on Anaconda and Windows 10 just like BMV2 works? (not more complicated?)

**2**.  Will it support same hardware, or need a much more powerful CPU / GPU compare to BMV2 ?

**3**.  Can you please tell when will you release it again, I missed it first so I can't test it because it's still offline.
It will be very nice to have it this week if possible of course.

Thanks ahead for the answers, please keep up the good work! ❤

**Comment by PeterL1n** [comment]
1. It should just work.
2. It is lighter and requires less powerful hardware.
3. Not sure.

**Comment by AlonDan** [comment]
Thanks for answering my questions :)
Since it's almost about 2 weeks since it's not available I hope that you will re-release it again soon.

Keep up the good work!

**Comment by PeterL1n** [comment]
I wish it too, but the legal team is just slow... Sorry about that. I have no time line so far.

**Comment by PeterL1n** [comment]
The code is now published.

**Comment by AlonDan** [comment]
> The code is now published.

Thanks for the update, I appreciate it! ❤
