### ISSUE TITLE
Error: Failed to parse model JSON of response from model/model.json

### ISSUE THREAD

**Issue by thoughtassassin** [PeterL1n/RobustVideoMatting#103]
I am trying to run the sample in the tfjs branch. I am serving the index.html using node. I created an app.js file to serve the index.html with node. I get this error:

![Screen Shot 2021-11-11 at 11 06 12 AM](https://user-images.githubusercontent.com/1539057/141342923-794f2afc-6a7c-4f90-a050-acdcc800ae1e.png)

I built a herokuapp to show the running code:

https://robust-video-mapping.herokuapp.com/

**Comment by PeterL1n** [comment]
Your node app setting is not right. The response content-type header for model.json is currently `text/html`. Should be `application/json`

![image](https://user-images.githubusercontent.com/7651753/141380810-d3dd94b2-908a-4095-9587-566d820d0b14.png)

**Comment by thoughtassassin** [comment]
Sorry about that. I set up an express app so I could serve the files properly. It is working perfectly now. Thank you for your help.

**Comment by CanyonWind** [comment]
Hi @thoughtassassin @PeterL1n , I'm new to javascript and this might sound elementary -- do you mind sharing some hints on how to set the content-type header correctly? I met the same problem when I used the build tool Parcel as suggested [here](https://www.tensorflow.org/js/tutorials/setup). Thanks a lot!
