### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.models.mobilenetv3' [colab]

### ISSUE THREAD

**Issue by kcky436348hdfg6** [PeterL1n/RobustVideoMatting#105]
Hi! Thanks you for your code and this colab! I already used it and it worked perfectly but today I got this error during "Start Inference" level: ModuleNotFoundError: No module named 'torchvision.models.mobilenetv3'
I'm bad at it. I'm sorry. Could you help me to beat this error please?

**Comment by PeterL1n** [comment]
Not using the latest torchvision. Update to latest torchvision should solve it.
