### ISSUE TITLE
about training loss

### ISSUE THREAD

**Issue by SiChuanJay** [PeterL1n/RobustVideoMatting#106]
你好，我们在使用rvm训练时，第二阶段训练完loss大概在0.05左右，但是到第三阶段的时候loss就变成了0.3，然后第四阶段训练完，loss最后到0.2左右。我们使用的数据集和参数都和文档中所写是一样的。请问是因为第三阶段使用hr图像的原因吗？

**Comment by PeterL1n** [comment]
对的，Stage3 会有 HR 和 LR 的 loss。
