### ISSUE TITLE
"return fgr, pha, *rec". SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hengshan123** [PeterL1n/RobustVideoMatting#107]
Hi,  我想把模型转为tflite，用tensorflow的分支转的时候发现一个语法错误，应该是python版本不同导致的，不知道作者的python是哪个版本。

**Comment by PeterL1n** [comment]
Python 3.7/3.8/3.9/3.10

**Comment by hengshan123** [comment]
多谢！

**Comment by droplet-js** [comment]
> Hi, 我想把模型转为tflite，用tensorflow的分支转的时候发现一个语法错误，应该是python版本不同导致的，不知道作者的python是哪个版本。

大佬，成功将模型转为 tflite 了吗？
