### ISSUE TITLE
pth转onnx

### ISSUE THREAD

**Issue by FengMu1995** [PeterL1n/RobustVideoMatting#108]
因为转完onnx后续还要转成别的格式，需要用onnx.infer_shape推理形状保存在模型中，可是在下图中，到shape这里推理的维度不是1,64,12,20而是4，不能把维度传给下一层，有什么办法能把那里的维度弄出来吗
![image](https://user-images.githubusercontent.com/52693361/142591204-bfc779a8-1e9f-4f96-a816-20d098fbd4c8.png)

**Comment by PeterL1n** [comment]
Shape的输出本来就是4。是一维向量 [B, H, W, C] = 4

**Comment by niujindacidian** [comment]
@FengMu1995  请问.pth怎么成功转换成.onnx，按照下边这么设置不会报错吗
    def export(self):
        rec = (torch.zeros([1, 1, 1, 1]).to(self.args.device, self.precision),) * 4
        src = torch.randn(1, 3, 1080, 1920).to(self.args.device, self.precision)

**Comment by PeterL1n** [comment]
@niujindacidian 看ONNX分支export_onnx.py https://github.com/PeterL1n/RobustVideoMatting/blob/onnx/export_onnx.py

**Comment by FengMu1995** [comment]
@niujindacidian 
按照作者那个代码没有报错

**Comment by queenmary55** [comment]
@FengMu1995 跟你遇到了一样的问题，我是在把onnx 进行onnxsim的时候遇到的（最终目的想转ncnn），一直报错说” Name:'Expand_174' Status Message: invalid expand shape“，应该就是expand这个操作得到shape那个维度不对。你现在这个问题解决了吗

**Comment by PeterL1n** [comment]
@queenmary55 ncnn 有人已经转了：https://github.com/FeiGeChuanShu/ncnn_Android_RobustVideoMatting

**Comment by queenmary55** [comment]
@PeterL1n 是的，我看到有人转成功了。我想尝试自己从pytorch转到ncnn，pytorch转onnx使用您的代码可以成功（只是有警告）；但是简化onnx这步就会报错，遇到的问题跟@FengMu1995  一样，expand这个节点会报错，说形状不对。

**Comment by PeterL1n** [comment]
You can remove the expand op. The expand op allows you to provide the initial hidden state as a 1x1x1x1 zero tensor and it automatically expands to the right size of BxCxHxW. You can remove expand, but in the runtime, you have to provide BxCxHxW zero tensor as the initial hidden state. You can compute C, H, W for all rXi yourself. If you only gonna run on one fixed resolution, you can hardcode the value.

The expand op is at: https://github.com/PeterL1n/RobustVideoMatting/blob/ebead27cb683e157b2bea7ca869daa820a07ba8f/model/decoder.py#L192

You can remove it.

Then you probably also want to change `dynamic_everything` to `dynamic_spatial` in https://github.com/PeterL1n/RobustVideoMatting/blob/ebead27cb683e157b2bea7ca869daa820a07ba8f/export_onnx.py#L65

**Comment by queenmary55** [comment]
@PeterL1n P 感谢您的讲解，我去试试

**Comment by FengMu1995** [comment]
@PeterL1n 
HardSigmoid公式应该是这个:
![Screenshot from 2021-12-08 11-22-26](https://user-images.githubusercontent.com/52693361/145143186-8a2d3e03-52f9-496a-aa97-b20db669d646.png)
按理说没有静态参数的啊,为什么导出onnx用netron看Hardsigmoid会有alpha参数，
![Screenshot from 2021-12-08 11-26-36](https://user-images.githubusercontent.com/52693361/145143220-30818c25-b1cd-47b0-8598-5789d90fecc0.png)

**Comment by PeterL1n** [comment]
@FengMu1995 Alpha = 1/6. See https://pytorch.org/docs/stable/generated/torch.nn.Hardsigmoid.html

![image](https://user-images.githubusercontent.com/7651753/145252454-ed429c17-2600-4602-a157-4094fcdce846.png)

**Comment by FengMu1995** [comment]
OK，I understand it is x*relu6(x+3)/6 的1/6. 
thank you!

**Comment by Jon-drugstore** [comment]
> 
did you solved this problem? Thanks
