### ISSUE TITLE
从Google和Flicker爬的背景图片，这些图片有什么要求吗？如果没有这批图片是不是复现不了论文结果？

### ISSUE THREAD

**Issue by pxEkin** [PeterL1n/RobustVideoMatting#11]

**Comment by PeterL1n** [comment]
与 Test Set 近似就行。具体使用的搜索关键词参考 Background Matting V2 论文

**Comment by pxEkin** [comment]
> 与 Test Set 近似就行。具体使用的搜索关键词参考 Background Matting V2 论文

好的  谢谢大佬，我先看看

**Comment by pxEkin** [comment]
> 与 Test Set 近似就行。具体使用的搜索关键词参考 Background Matting V2 论文

MBV2关键字：
irport interior attic bar interior
bathroom beach city
church interior classroom interior empty city
forest garage interior gym interior
house outdoor interior kitchen
lab interior landscape lecture hall
mall interior night club interior office
rainy woods rooftop stadium interior
theater interior train station warehouse interior
workplace interior

有几个疑问：
1.每个关键字爬下来的图片都很多，每个关键字场景取多少背景图呢？
2.爬下来的图片需要做额外的前处理吗？比如crop，padding等
3.背景图片需要保持高分辨率吗？

**Comment by PeterL1n** [comment]
1. 你看情况吧，我们总共用了8000张。
2. 没有cropping，但我们每张图过 YOLO5 确保背景图片里没有人物。
3. 要

**Comment by jackzpp12** [comment]
大佬，怎么测试单张图片

**Comment by niujindacidian** [comment]
您好，请问一下，背景图片分辨率不高对结果会有什么影响吗？
