### ISSUE TITLE
Colab notebook: ModuleNotFoundError: No module named 'torchvision.models.utils'

### ISSUE THREAD

**Issue by TatianaSnauwaert** [PeterL1n/RobustVideoMatting#110]
Hi!

I am trying to run a colab notebook you provided but getting the following error:
![Screenshot from 2021-11-23 17-02-37](https://user-images.githubusercontent.com/63235607/143059621-8050c16c-d949-4ece-a507-64d059a47954.png)

I then tried to clone your repository and use it locally, I was also getting this error. Looks like load_state_dict_from_url is not available from torchvision.models.utils. However when I change this line to:
from **torch.hub** import load_state_dict_from_url

then it works. Unfortunately, I couldn't finish testing your method locally due to cuda issues. Could you please fix the colab, so it is possible to test things there?

Thanks in advance and congrats on your work, it looks impressive!

**Comment by PeterL1n** [comment]
Fixed.
