### ISSUE TITLE
ncnn推理问题

### ISSUE THREAD

**Issue by FengMu1995** [PeterL1n/RobustVideoMatting#112]
ncnn模型推理源码为什么是两个原图输入
ncnn_in = ncnn::Mat::from_pixels_resize(rgb.data,ncnn::Mat::PIXEL_RGB, rgb.cols, rgb.rows,512,512);//
ncnn_in1 = ncnn::Mat::from_pixels_resize(rgb.data,ncnn::Mat::PIXEL_RGB, rgb.cols, rgb.rows,256,256);
ex_face.input("src1", ncnn_in1);
ex_face.input("src2", ncnn_in);

**Comment by PeterL1n** [comment]
问他啊
