### ISSUE TITLE
复杂背景下模型鲁棒性提升

### ISSUE THREAD

**Issue by SiChuanJay** [PeterL1n/RobustVideoMatting#113]
作者您好，请问有什么方法可以提升模型在复杂背景下的鲁棒性，我这边尝试了加入复杂的背景数据集，但是效果仍不太理想，希望您能给出一些建议，非常感谢！

**Comment by PeterL1n** [comment]
如果在这个模型基础上，那就只能加大模型参数量了，Backbone可以换成ResNet50或ResNet101，或者试试最新的RegNet系列。换更大的Backbone应该会有比较大的提升，应为从Segmentation的角度来看，大模型应该有一较大的提升。 LR-ASPP和Recurrent Decoder可以加大channels数量。这样会增加训练时的内存占用，你可以放弃高分辨率下训练Deep Guided Filter转而用不用训练的Fast Guided Filter，效果差不多。

当然，你也可以完全重新设计模型构架。
