### ISSUE TITLE
解码部分输出通道如何确定？

### ISSUE THREAD

**Issue by niujindacidian** [PeterL1n/RobustVideoMatting#115]
您好，想请问model.py中解码部分的输出通道数是如何设定的[80, 40, 32, 16]，有什么依据吗？
if variant == 'mobilenetv3':
            self.backbone = MobileNetV3LargeEncoder(pretrained_backbone)
            self.aspp = LRASPP(960, 128)
            self.decoder = RecurrentDecoder([16, 24, 40, 128], [80, 40, 32, 16])

**Comment by PeterL1n** [comment]
通过手动尝试，对比了几组效果和效率。你可以自己调其他的。

**Comment by niujindacidian** [comment]
好的，谢谢。
