### ISSUE TITLE
Why is youtubevis seg resized with bilinear?

### ISSUE THREAD

**Issue by haichaoyu** [PeterL1n/RobustVideoMatting#119]
Hi Peter,

Thanks for the great repo. One question regarding the code: why is the youtubevis labels resized with bilinear mode? Should it be nearest as the other datasets?

https://github.com/PeterL1n/RobustVideoMatting/blob/master/dataset/youtubevis.py#L109

Thanks.

**Comment by PeterL1n** [comment]
I guess you can change it to NEAREST. Shouldn't matter too much.
