### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by li-wenquan** [PeterL1n/RobustVideoMatting#122]
你好，请教个问题：
1、通过制作一个新的video matting数据集作为RVM的最后阶段训练是否可行？还是应该混合VideoMatte240K从头训练？
     谢谢。

**Comment by PeterL1n** [comment]
用RVM的weights开始会比较容易

**Comment by surifans** [comment]
> 



> 你好，请教个问题： 1、通过制作一个新的video matting数据集作为RVM的最后阶段训练是否可行？还是应该混合VideoMatte240K从头训练？ 谢谢。

你可以考虑用AE抠图制作数据集，VideoMatte240K很多数据就是AE抠图制作的

**Comment by li-wenquan** [comment]
> > 
> 
> > 你好，请教个问题： 1、通过制作一个新的video matting数据集作为RVM的最后阶段训练是否可行？还是应该混合VideoMatte240K从头训练？ 谢谢。
> 
> 你可以考虑用AE抠图制作数据集，VideoMatte240K很多数据就是AE抠图制作的

好的，谢谢。
