### ISSUE TITLE
a bug about youtubevis.py

### ISSUE THREAD

**Issue by cakesibyl** [PeterL1n/RobustVideoMatting#129]
https://github.com/PeterL1n/RobustVideoMatting/blob/master/dataset/youtubevis.py#L41

self.videos[video_id] is a dict,  dict_keys(['license', 'coco_url', 'height', 'width', 'length', 'date_captured', 'file_names', 'flickr_url', 'id']),
len(self.videos[video_id]) is equal to 9, is not a frame id.
it should be len(self.videos[video_id]['file_names']).

**Comment by PeterL1n** [comment]
Fixed.
