### ISSUE TITLE
Core ML 导出包报错

### ISSUE THREAD

**Issue by WJHCode** [PeterL1n/RobustVideoMatting#130]
导出参数里的--checkpoint rvm_mobilenetv3.pth 无法找到，

报错：
FileNotFoundError: [Errno 2] No such file or directory: 'rvm_mobilenetv3.pth'

**Comment by PeterL1n** [comment]
You have to download the PyTorch weights. https://github.com/PeterL1n/RobustVideoMatting/releases/download/v1.0.0/rvm_mobilenetv3.pth

**Comment by WJHCode** [comment]
请问，这个文件放到什么位置？
