### ISSUE TITLE
A question about training

### ISSUE THREAD

**Issue by Asthestarsfalll** [PeterL1n/RobustVideoMatting#133]
In training stage 2,  `T` will be increased to 50 to force the network see longer sequences and learn long-term dependencies.
However, I think we will never set `T` as 50 in practical applications, It's a conflict for `RVM` which is a  real-time matting method.
And the training only lasts 2 epoch.
So is the stage 2 necessary？Is there any experiments to prove the role of stage 2?
Looking forward to your reply!

**Comment by PeterL1n** [comment]
T=50 is only 2 seconds of videos for 25fps. In real life the videos can be much longer. It is important for the model to adapt to long sequences.
