### ISSUE TITLE
float16的onnx模型导出

### ISSUE THREAD

**Issue by SiChuanJay** [PeterL1n/RobustVideoMatting#134]
您好，我再使用您们提供的导出代码时，导出float32格式的onnx可以正常使用，但是在导出float16的时候遇到了问题，数据输入的时候是float16，但是output仍然是float32格式的，请问这是怎么回事？

**Comment by SiChuanJay** [comment]
![1642162466(1)](https://user-images.githubusercontent.com/52130681/149513940-4e1e8b7c-7d8a-4f9a-a6e1-86f6a645ceaa.jpg)

**Comment by havely-c** [comment]
请问您是用什么平台使用onnx的呢T

**Comment by liushuailxx** [comment]
同上，用了x86 及 nvidia jetson xavier 都是一样的结果，输入是float16,输出为float32

**Comment by cvDFT** [comment]
> ![1642162466(1)](https://user-images.githubusercontent.com/52130681/149513940-4e1e8b7c-7d8a-4f9a-a6e1-86f6a645ceaa.jpg)

我也遇到了这个问题，请问您解决了吗

**Comment by PeterL1n** [comment]
官方的 ONNX FP16 模型的输入输出都是 FP16 的。不知道为什么你们导出的不对。也许可以尝试切换回旧版 Pytorch。用requirements.txt里的版本

**Comment by zhanghongyong123456** [comment]
> ![1642162466(1)](https://user-images.githubusercontent.com/52130681/149513940-4e1e8b7c-7d8a-4f9a-a6e1-86f6a645ceaa.jpg)



> > ![1642162466(1)](https://user-images.githubusercontent.com/52130681/149513940-4e1e8b7c-7d8a-4f9a-a6e1-86f6a645ceaa.jpg)
> 
> 我也遇到了这个问题，请问您解决了吗

我采用的pytorch1.9 cuda10.2  转换的结果也是一样的，请问这个问题解决了吗

**Comment by cvDFT** [comment]
> 

貌似不影响使用
