### ISSUE TITLE
Can an HD version of the preprocessed background video be provided?

### ISSUE THREAD

**Issue by li-wenquan** [PeterL1n/RobustVideoMatting#140]
你好，请教一下，对于背景视频，训练过程中除了低分辨率版本外似乎还需要高分辨率版本？在训练文档中，我只找到低分辨率版本的背景视频（预处理版本），你是否愿意提供你们预处理后的高清版本？谢谢。

**Comment by PeterL1n** [comment]
I remember the video backgrounds provided are high resolution.

**Comment by li-wenquan** [comment]
我根据你提供的链接，我下载后看到的视频帧的分辨率是768 X 432

**Comment by PeterL1n** [comment]
I guess that's all I have. You can extract them from the source yourself. The videos are from DVM paper.
