### ISSUE TITLE
我尝试固定r1x和downsample_ratio将model转成onnx，但是效果很差

### ISSUE THREAD

**Issue by Sourishlemon** [PeterL1n/RobustVideoMatting#141]
![image](https://user-images.githubusercontent.com/72776705/154890306-c82730d0-873e-4e68-8329-b15da36b673c.png)
我只修改了model，并自己建了个Exporter.py导出为onnx
![image](https://user-images.githubusercontent.com/72776705/154914081-3025de6f-fcfa-4b88-8ccf-29a96001a312.png)
`import argparse

import torch

from model import MattingNetwork

class Exporter:
    def __init__(self):
        self.parse_args()
        self.init_model()
        self.export()

    def parse_args(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('--model-variant', type=str, required=True, choices=['mobilenetv3', 'resnet50'])
        parser.add_argument('--model-refiner', type=str, default='deep_guided_filter',
                            choices=['deep_guided_filter', 'fast_guided_filter'])
        parser.add_argument('--precision', type=str, required=True, choices=['float16', 'float32'])
        parser.add_argument('--opset', type=int, required=True)
        parser.add_argument('--device', type=str, required=True)
        parser.add_argument('--checkpoint', type=str, required=False)
        parser.add_argument('--output', type=str, required=True)
        self.args = parser.parse_args()

    def init_model(self):
        self.precision = torch.float32 if self.args.precision == 'float32' else torch.float16
        self.model = MattingNetwork(self.args.model_variant, self.args.model_refiner).eval().to(self.args.device,
                                                                                                self.precision)
        if self.args.checkpoint is not None:
            self.model.load_state_dict(torch.load(self.args.checkpoint, map_location=self.args.device), strict=False)

    def export(self):
        # rec = (torch.zeros([1, 1, 1, 1]).to(self.args.device, self.precision),) * 4
        src = torch.randn(1, 3, 720, 1280).to(self.args.device, self.precision)
        r1i = torch.randn(1, 16, 135, 240).to(self.args.device, self.precision)
        r2i = torch.randn(1, 20, 68, 120).to(self.args.device, self.precision)
        r3i = torch.randn(1, 40, 34, 60).to(self.args.device, self.precision)
        r4i = torch.randn(1, 64, 17, 30).to(self.args.device, self.precision)
        # 假设你的model的forward方法，已经指定downsample_ratio的默认值为torch.tensor([0.375]).
        # downsample_ratio = torch.tensor([0.375]).to(self.args.device)

        torch.onnx.export(
            self.model,
            (src, r1i, r2i, r3i, r4i),  # 不需要导出downsample_ratio，直接使用默认值
            self.args.output,
            export_params=True,
            opset_version=self.args.opset,
            do_constant_folding=True,
            input_names=['src', 'r1i', 'r2i', 'r3i', 'r4i'],  # 不需要导出downsample_ratio，直接使用默认值
            output_names=['fgr', 'pha', 'r1o', 'r2o', 'r3o', 'r4o'])

export =  Exporter()`
请你帮忙看下怎么回事

**Comment by lcc157** [comment]
请问 现在好了嘛
