### ISSUE TITLE
Problem with the ONNX model - Error OnnxImportException: Unknown type Scan encountered while parsing layer UU002UU.

### ISSUE THREAD

**Issue by karen-velasquez** [PeterL1n/RobustVideoMatting#143]
Hello, I haven't been using Unity for a long time, I created an onnx file of a KNeighborsClassifier model but when trying to read this model in Unity with Barracuda it gives me the following error:

OnnxImportException: Unknown type Scan encountered while parsing layer UU002UU.
Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage)

and also the error:

 OnnxImportException: Unknown type Scan encountered while parsing layer UU002UU.

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3394)

I think the error is when I convert the model from KNeighborsClassifier to Onnx, could you help me with this problem?

This is the code with which I converted my model to ONNX
----------------------------------------------------------------------
import pandas as pd
path='https://raw.githubusercontent.com/iannjari/datasets/main/diabetes.csv'
df=pd.read_csv(path,engine='python')
target_name = "Outcome"
target = df[target_name]
data = df.drop(columns=[target_name])

# Train a model.
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
X_train, X_test, y_train, y_test = train_test_split(data,target, test_size=0.30, random_state=42)
knn = KNeighborsClassifier(n_neighbors = 1)
# Fit the classifier to the data
knn.fit(X_train,y_train)
print(knn.score(X_test, y_test))

# Convert into ONNX format
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
initial_type = [('float_input', FloatTensorType([None, 8]))]
onx = convert_sklearn(knn, initial_types=initial_type)
with open("/content/drive/MyDrive/Colab Notebooks/model/knn_test.onnx", "wb") as f:
    f.write(onx.SerializeToString())

# Compute the prediction with ONNX Runtime
import onnxruntime as rt
import numpy
sess = rt.InferenceSession("/content/drive/MyDrive/Colab Notebooks/model/knn_test.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
print(type(X_test))
X_test_numpy=X_test.to_numpy()
print(X_test_numpy)
pred_onx = sess.run([label_name], {input_name: X_test_numpy.astype(numpy.float32)})[0]
print(pred_onx)

**Comment by romygt** [comment]
@PeterL1n @karen-velasquez did you solve this
