### ISSUE TITLE
Separate multiple people

### ISSUE THREAD

**Issue by Echolink50** [PeterL1n/RobustVideoMatting#145]
Everything is working great. I was wondering if it was possible to get 2 different masks if 2 people are in the video? Like if I want to have each person separate or just have 1 person on the green back ground? Thanks everyone

**Comment by PeterL1n** [comment]
No. Not from this model.

**Comment by Echolink50** [comment]
Thank you. Anybody know of an ai that does anything like that? Thanks

**Comment by PeterL1n** [comment]
Look into instance segmentation methods.
