### ISSUE TITLE
作者大大有没有尝试把GRU结构和分割网络解耦训练？

### ISSUE THREAD

**Issue by surifans** [PeterL1n/RobustVideoMatting#147]
目前GRU结构和分割网络在读取时序数据时会一起进行训练，一起更新参数，这样它们的耦合度会很高的吧？
但是实际上在训练图像分割网络的时候，如果把连续的帧作为一个batch拿进去训练，网络是很难收敛的。
不知道有没有大佬试过先训练好分割网络，然后锁死分割网络的参数，然后再训练GRU结构的参数，这样分割网络和GRU结构的耦合度会大大降低，会不会实现1+1=2的效果？

**Comment by Jon-drugstore** [comment]
> 目前GRU结构和分割网络在读取时序数据时会一起进行训练，一起更新参数，这样它们的耦合度会很高的吧？ 但是实际上在训练图像分割网络的时候，如果把连续的帧作为一个batch拿进去训练，网络是很难收敛的。 不知道有没有大佬试过先训练好分割网络，然后锁死分割网络的参数，然后再训练GRU结构的参数，这样分割网络和GRU结构的耦合度会大大降低，会不会实现1+1=2的效果？

请教一下，你好，请问8000张背景图，需要分辨率也很高么？相关问题可以讨论一下，qq: 1126013917, 谢谢

**Comment by tayton42** [comment]
我觉得这个想法很有道理...请问您尝试了吗

**Comment by LiYufengzz** [comment]
请问你尝试了吗？效果怎么样
