### ISSUE TITLE
foreground prediction details

### ISSUE THREAD

**Issue by li-wenquan** [PeterL1n/RobustVideoMatting#148]
你好，请教一下，关于前景预测，从官方提供的web demo中,我看到模型预测的前景图片中除了前景(人像)外，还存在输入图片的背景细节（非人像像素），但是我自己训练得到的模型（我的模型没有修改官方的任何细节，唯一的不同仅仅是采用我采集而来的背景图片），预测的前景图片只含有人像而不会存在输入图片的背景细节，一开始我怀疑可能是前景loss包含了所有像素（alpha可以是任何值而不仅仅是像论文中所说的大于0）的loss, 但是我查看代码后没有任何问题，和论文一致，请问这是什么原因造成？  谢谢。

**Comment by PeterL1n** [comment]
”还存在输入图片的背景细节（非人像像素）“ 具体指什么？

**Comment by li-wenquan** [comment]
![0000](https://user-images.githubusercontent.com/38526026/160103120-40a39636-ce5a-4013-886c-f27833035352.jpg)
![0000](https://user-images.githubusercontent.com/38526026/160103156-0431dd87-a553-4869-9e61-281c53b6ecc4.jpg)
第一张是官方的前景预测结果，第二张是我的前景预测结果

**Comment by PeterL1n** [comment]
Training on stage 4 with distinctions and adobe dataset help enforces foreground. Maybe you didn't finish the training?
