### ISSUE TITLE
FP16 is slower than FP32

### ISSUE THREAD

**Issue by ZachL1** [PeterL1n/RobustVideoMatting#149]
I use pre-trained ONNX model parameters for inference tests (in Python not C++), only onnxruntime, cv2 and numpy libraries, nothing extra. Parameters downloaded from [https://github.com/PeterL1n/RobustVideoMatting/releases/](https://github.com/PeterL1n/RobustVideoMatting/releases/): `rvm_mobilenetv3_fp32.onnx` and `rvm_mobilenetv3_fp16.onnx`

Inference on 1080x1920 video，`downsample_ratio=0.25`. As a result, the speed of FP32 is about 170ms (1 frame), and the speed of FP16 is about 240ms. Why is FP16 so slow?

I have adjusted the input correctly, for `src, r1i, r2i, r3i, r4i` it is `np.array([[[[]]]], dtype=np.float32 or 16)` and for `downsample_ratio` it is always `np.array([0.25], dtype= float32)`

I use CPU (Intel i5) for inference, Is it so slow because the CPU does not support FP16 operations?

**Comment by cvDFT** [comment]
cpu确实不支持

**Comment by ZachL1** [comment]
@cvDFT  谢谢你的回答！

我对 CPU 的浮点运算不太了解，请问可以展开详细说说吗？非常感谢！

**Comment by PeterL1n** [comment]
可能 Onnxruntime 的某些运算不支持CPU FP16，必须转换成FP32处理再转换回来，这会影响性能。发布的 FP16 模型在 GPU 上是和 FP32 差不多速度的。
