### ISSUE TITLE
tf_saved_model 模型调用问题

### ISSUE THREAD

**Issue by zuixiaosanlang** [PeterL1n/RobustVideoMatting#151]
![image](https://user-images.githubusercontent.com/20105627/159857330-8868638f-fed7-417d-8425-a6e60bffc247.png)

![image](https://user-images.githubusercontent.com/20105627/159859639-689f2186-42ca-4de6-9189-8e6d3691e6f9.png)

请问 tf_saved_model 的模型该怎么调用呢？？  以前没碰过这样的输入参数，试了好几种都报错

**Comment by PeterL1n** [comment]
看示范文档：
英文：https://github.com/PeterL1n/RobustVideoMatting/blob/master/documentation/inference.md#tensorflow
中文：https://github.com/PeterL1n/RobustVideoMatting/blob/master/documentation/inference_zh_Hans.md#tensorflow
