### ISSUE TITLE
GRU门在代码中的实现与论文中的差异

### ISSUE THREAD

**Issue by ztysdu** [PeterL1n/RobustVideoMatting#152]
![image](https://user-images.githubusercontent.com/69748689/160265067-e7fbdb91-494e-4acf-86ad-750aa02e18c4.png)
论文中是这样的,而在代码中是这样的
![image](https://user-images.githubusercontent.com/69748689/160265120-b9b0a7ec-0dee-4a40-87ed-626de5acd14e.png)

请问返回的第一个h是否应该是c,以及是否应该是蓝笔写的公式
我刚开始接触深度学习,可能不太了解这里面的一些机制,如果我理解的不对耽误了您的时间见谅

**Comment by PeterL1n** [comment]
代码没问题。

第一个是 output 第二个是 hidden。GRU不同于LSTM，GRU的输出即是循环隐值。这么写只是让代码更容易而已。

**Comment by ztysdu** [comment]
明白了,我误解了您论文中的ot,它是候选隐状态.蟹蟹!
