### ISSUE TITLE
隐状态在训练过程中的调用位置？

### ISSUE THREAD

**Issue by nicolaus-huang** [PeterL1n/RobustVideoMatting#153]
你好,我想问一下在训练过程中是否没有使用隐状态?
![P$S763H7{ALZ2OM7HMGS0 5](https://user-images.githubusercontent.com/57386430/160282379-edf95491-aba1-49e8-ba17-607acfa48f23.JPG)

而在推理中,
![AP9GAKRGH%PZSC@C2F8V@OL](https://user-images.githubusercontent.com/57386430/160282386-32caafd1-4a1e-4fb5-be03-8ec0789ceda1.JPG)

rec存储了隐状态

**Comment by PeterL1n** [comment]
用了。训练时的batch是五维BTCHW。模型内部循环使用隐藏值。
