### ISSUE TITLE
发现推理代码似乎有点问题

### ISSUE THREAD

**Issue by surifans** [PeterL1n/RobustVideoMatting#158]
为什么inference.py中auto_downsample_ratio函数里面算缩放比例是min(512 / max(h, w), 1)，而训练的时候数据处理缩放_downsample_if_needed函数里面算缩放比例是scale = self.size / min(w, h)？一个是max(h, w)，一个是min(w, h)，这里有问题吧？

**Comment by surifans** [comment]
计算了下推理的时候缩放比例为min(512 / max(h, w), 1)和缩放比例是min(512 / min(h, w), 1)的精度几乎是一样的。
可能是训练的时候加入了随机尺寸大小进行训练，所以在一定范围内不同尺寸大小的输入精度是一样的~

**Comment by PeterL1n** [comment]
你可以理解为缩放的 Fill 和 Fit 模式，

inference 时用的是 Fit，最大边512。

training 在 dataloading 时用的是 Fill，最小边512，这样裁剪后没有黑边。
