### ISSUE TITLE
推理速度是2~3帧每秒

### ISSUE THREAD

**Issue by napohou** [PeterL1n/RobustVideoMatting#159]
V100的GPU，用的模型是预训练的mobilenetv3.pth，视频是1920*1080的，请问是不是太慢？

**Comment by napohou** [comment]
GPU占用很低，经常在3%左右

**Comment by PeterL1n** [comment]
inference.py 的 video encoding 和 decoding 不是 hardware accelerate 的。你要自己写硬件加速的推理
