### ISSUE TITLE
Object and human 

### ISSUE THREAD

**Issue by gianlucafico** [PeterL1n/RobustVideoMatting#162]
This is not an issue, but a request if it's possible.. Is there a way to tell the script that i need other than a human subject also a bicycle, a basktball etc etc...

I use your script in my unreal engine project and I thank you so much for what you have done!!

**Comment by PeterL1n** [comment]
You can check out BackgroundMattingV2. That model requires you to provide a pre-captured background, which allows the model to differentiate what objects are in the foreground.
