### ISSUE TITLE
如果只要训练image matting，如何修改模型 

### ISSUE THREAD

**Issue by tengshaofeng** [PeterL1n/RobustVideoMatting#166]
亲爱的作者，我一直关注你近年来的matting工作，每个都很棒，令人印象深刻。尤其是这一个伟大的作品，不需要背景作为输入，但是通过其他的issue了解到这个是为视频设计的。那么我的问题来了，如果我只想要训练图片抠图呢，是不是把gru部分去掉，其他的参照你的就好了？还是你有推荐的其他结构吗

**Comment by PeterL1n** [comment]
如果你是想直接用现有的模型，图片相当于单帧视频。只不过GRU没什么用途了。推理文档里有写怎么使用。
如果你是要自己训练新模型，那就自己研究吧。

**Comment by tengshaofeng** [comment]
我要自己训练新模型，针对图片的抠图，那看来是要自己研究新模型了
