### ISSUE TITLE
大佬，如何测试单张图片

### ISSUE THREAD

**Issue by jackzpp12** [PeterL1n/RobustVideoMatting#17]
大佬，如何测试单张图片

**Comment by PeterL1n** [comment]
我们没有提供单张图片的 inference python script，但你可以自己写。

**Comment by Sostay** [comment]
> 我们没有提供单张图片的 inference python script，但你可以自己写。

demo页面不支持edge浏览器吗？

**Comment by PeterL1n** [comment]
@Sostay 不清楚，应该没问题啊，不行就用Chrome
