### ISSUE TITLE
请问有一个数据集未公开，该如何进行训练呢

### ISSUE THREAD

**Issue by chainsean** [PeterL1n/RobustVideoMatting#172]
![image](https://user-images.githubusercontent.com/101028617/168224342-e65657aa-c2a1-49b3-af12-b7a7aa97d8c7.png)
Image Backgrounds
Train set:
We crawled 8000 suitable images from Google and Flicker.
We will not publish these images.

background_image_dir=DATA_PATHS['background_images']['train'],
这个数据集未公开，请问能申请下这个数据集进行训练吗

**Comment by PeterL1n** [comment]
得自己爬图
