### ISSUE TITLE
关于训练中的网络内循环对GRU的训练

### ISSUE THREAD

**Issue by tayton42** [PeterL1n/RobustVideoMatting#201]
#18 #74 #153 作者你好，你在以上问题中提到训练时的GRU隐藏状态会通过网络内部循环训练，我没能理解，内部循环发生在什么部分？是在
`self.model_ddp(true_src, downsample_ratio=downsample_ratio)[:2]`中进行的吗，model中输出的*rec是如何传入r1r2r3r4的呢，因为我想在Projection中添加一个循环网络，我不确定它的隐藏状态是否学习到了

**Comment by PeterL1n** [comment]
https://github.com/PeterL1n/RobustVideoMatting/blob/81a10937c73f68eeddb863221c61fe6a60a1cca2/model/decoder.py#L176

**Comment by PeterL1n** [comment]
当输入为5维 [b, t, c, h, w] 的 tensor 时，不是GRU的部分可以把 B 和 T 合并加速，GRU部分内部循环 T，模型会输出 [b, t, c, h, w] 的结果和 [b, c, h, w] 的 hidden 做循环。hidden 是最后一帧产生的，可以给模型用于下一批次的 [b, t, c, h, w] 输入。
