### ISSUE TITLE
How do I display results locally using a local camera

### ISSUE THREAD

**Issue by mayingwuhu** [PeterL1n/RobustVideoMatting#204]
I really want to display the result locally using a local camera. I notice that inference_utils.py use pims.PyAVVideoReader to get the imformation about the video. So I really want to know how to call the local camera.

**Comment by kevinpl07** [comment]
```python
import cv2
import torch
from torchvision import transforms
from model import MattingNetwork
import numpy as np

import time

device = torch.device('cpu')
model = MattingNetwork('mobilenetv3').eval()
model.load_state_dict(torch.load('rvm_mobilenetv3.pth'))
model = model.to(device=device, dtype=torch.float32).eval()


bgr = torch.tensor([.47, 1, .6]).view(3, 1, 1)
rec = [None] * 4                                       # Initial recurrent states.
downsample_ratio = 0.125

cap = cv2.VideoCapture(0)

transform = transforms.Compose([
            # transforms.Resize(input_resize[::-1]),
            transforms.ToTensor()
        ])
with torch.no_grad():
    while True:

        success, img = cap.read()
        src = transform(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        src = src.to(device, torch.float32, non_blocking=True).unsqueeze(0) # [B, T, C, H, W]
        start = time.time()
        fgr, pha, *rec = model(src, *rec, downsample_ratio)  # Cycle the recurrent states.
        end = time.time()
        print(end-start)
        com = fgr * pha + bgr * (1 - pha)
        output = (np.swapaxes(com.numpy()[0].T ,0,1)* 255).astype(np.uint8)
        output = cv2.cvtColor(output, cv2.COLOR_RGB2BGR)
        cv2.imshow("asd", output)
        if cv2.waitKey(5) & 0xFF == 27:
            break
```

**Comment by mp075496706** [comment]
> ```python
> import cv2
> import torch
> from torchvision import transforms
> from model import MattingNetwork
> import numpy as np
> 
> import time
> 
> device = torch.device('cpu')
> model = MattingNetwork('mobilenetv3').eval()
> model.load_state_dict(torch.load('rvm_mobilenetv3.pth'))
> model = model.to(device=device, dtype=torch.float32).eval()
> 
> 
> bgr = torch.tensor([.47, 1, .6]).view(3, 1, 1)
> rec = [None] * 4                                       # Initial recurrent states.
> downsample_ratio = 0.125
> 
> cap = cv2.VideoCapture(0)
> 
> transform = transforms.Compose([
>             # transforms.Resize(input_resize[::-1]),
>             transforms.ToTensor()
>         ])
> with torch.no_grad():
>     while True:
> 
>         success, img = cap.read()
>         src = transform(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
>         src = src.to(device, torch.float32, non_blocking=True).unsqueeze(0) # [B, T, C, H, W]
>         start = time.time()
>         fgr, pha, *rec = model(src, *rec, downsample_ratio)  # Cycle the recurrent states.
>         end = time.time()
>         print(end-start)
>         com = fgr * pha + bgr * (1 - pha)
>         output = (np.swapaxes(com.numpy()[0].T ,0,1)* 255).astype(np.uint8)
>         output = cv2.cvtColor(output, cv2.COLOR_RGB2BGR)
>         cv2.imshow("asd", output)
>         if cv2.waitKey(5) & 0xFF == 27:
>             break
> ```

GPU inference can also be used in this way:
~~~
import cv2
import torch
from torchvision import transforms
from model import MattingNetwork
import numpy as np

import time

device = torch.device('cuda:0')
model = MattingNetwork('mobilenetv3').eval()
model.load_state_dict(torch.load('./models/rvm_mobilenetv3.pth'))
model = model.to(device=device, dtype=torch.float16).eval()


bgr = torch.tensor([.47, 1, .6]).view(3, 1, 1).cuda()
rec = [None] * 4                                       # Initial recurrent states.
downsample_ratio = 0.125

cap = cv2.VideoCapture(0)

transform = transforms.Compose([
            # transforms.Resize(input_resize[::-1]),
            transforms.ToTensor()
        ])
with torch.no_grad():
    while True:

        success, img = cap.read()
        src = transform(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        src = src.to(device, torch.float16, non_blocking=True).unsqueeze(0) # [B, T, C, H, W]
        start = time.time()
        fgr, pha, *rec = model(src, *rec, downsample_ratio)  # Cycle the recurrent states.
        end = time.time()
        print(end-start)
        com = fgr * pha + bgr * (1 - pha)
        output = (np.swapaxes(com.cpu().numpy()[0].T ,0,1)* 255).astype(np.uint8)
        output = cv2.cvtColor(output, cv2.COLOR_RGB2BGR)
        cv2.imshow("Preview", output)
        if cv2.waitKey(5) & 0xFF == 27:
            break
~~~

**Comment by mayingwuhu** [comment]
Really thank you guys！！！You are totally resolve my problem!
