### ISSUE TITLE
没看懂代码是怎么利用时间信息的，代码里的R1,r2,r3,r4。没见到过有被复用

### ISSUE THREAD

**Issue by josnname** [PeterL1n/RobustVideoMatting#208]
![image](https://user-images.githubusercontent.com/28743778/201511813-37919db1-3e0f-461d-bf1d-ee8055891047.png)
![image](https://user-images.githubusercontent.com/28743778/201511840-b56a9528-7e98-4051-b4a7-e3ca3af4d9bd.png)
![image](https://user-images.githubusercontent.com/28743778/201511855-d2e266bf-65fa-46aa-a185-6a2c8bf23553.png)
r1,r2,r3,r4重来没被复用过。所以一直都是全为0的张量

**Comment by PeterL1n** [comment]
During training, the input is a five-dimensional tensor [B, T, C, H, W]. Multiple frames are given in T together and there is an internal for loop. r1, r2, r3, r4 are never used for training. They are used for inference when your video sequence is much longer and you cannot fit all frames to the GPU, then you can fit T frames as a batch and cycle the rX tensors.

**Comment by josnname** [comment]
看懂了，感谢您的解答
