### ISSUE TITLE
关于第四阶段中对GRU的训练

### ISSUE THREAD

**Issue by tayton42** [PeterL1n/RobustVideoMatting#209]
请问第四阶段的训练为独立图片训练，但仍然以一定的序列长度输入网络，GRU也会尝试学习不相干图片之间的帧间信息，这不会对GRU造成干扰吗？如果我将GRU学习率在第四阶段设为0，是否会更好呢，谢谢

**Comment by PeterL1n** [comment]
It has temporal augmentation, so the input is not still images. It has motions.
