### ISSUE TITLE
推理完后 GPU 没释放

### ISSUE THREAD

**Issue by veasion** [PeterL1n/RobustVideoMatting#256]
执行 convert_video 函数，GPU 没有被释放 ：
```
import time
import torch
from model import MattingNetwork
from inference import convert_video

model = MattingNetwork('mobilenetv3').eval().cuda()
model.load_state_dict(torch.load('checkpoints/rvm_mobilenetv3.pth'))
convert_video(
	model,
	input_source='input.mp4',
	output_type='video',
	output_alpha='alpha.mp4',
	output_video_mbps=1,
	downsample_ratio=None,
	seq_chunk=12
)
time.sleep(10000)
 ```

**Comment by biubiue** [comment]
> 执行 convert_video 函数，GPU 没有被释放 ：
> 
> ```
> import time
> import torch
> from model import MattingNetwork
> from inference import convert_video
> 
> model = MattingNetwork('mobilenetv3').eval().cuda()
> model.load_state_dict(torch.load('checkpoints/rvm_mobilenetv3.pth'))
> convert_video(
> 	model,
> 	input_source='input.mp4',
> 	output_type='video',
> 	output_alpha='alpha.mp4',
> 	output_video_mbps=1,
> 	downsample_ratio=None,
> 	seq_chunk=12
> )
> time.sleep(10000)
> ```
解决了么，兄弟

**Comment by veasion** [comment]
在推理代码后面手动清理一下gpu缓存
```
torch.cuda.empty_cache()
```
