### ISSUE TITLE
1060的显卡能提升多少性能？（相对cpu）

### ISSUE THREAD

**Issue by zhaoyuan020** [PeterL1n/RobustVideoMatting#30]

**Comment by PeterL1n** [comment]
没有测过，但我觉得但凡是GPU都会比CPU快很多。

**Comment by bxjxxyy** [comment]
8700+1070的笔记本  一开始默认装的是pytorch cpu的，跑摄像头实时的1280*720的，只有1fps。后来换成pytorch gpu之后，是17fps
