### ISSUE TITLE
请问训练时，模型输出的3通道的fgr的groud truth是什么？

### ISSUE THREAD

**Issue by chenying99** [PeterL1n/RobustVideoMatting#31]
感谢大神分享，请教一个很菜的问题，模型输出的3通道的fgr的groud truth是什么呢？

我下载数据集VideoMatte240K中的 JPEG SD Format (6GB)，查看fgr目录中的图片，抽样目测其中大部分背景是黑色的，还有少部分是白色的？

如果我有数据集用于训练，只包含原始图像和pha(matte)， 那怎么处理得到这个fgr的groud truth呢？

另外， VideoMatte240K数据集只有fgr目录与pha目录；训练时，模型输入的true_src图像，是根据pha与另外的背景图像合成的吗？

还请教一个问题， 模型输出*rec （r1, r2, r3, r4），训练时是不用监督的吧？即不用groud truth监督训练的吧？  谢谢

**Comment by PeterL1n** [comment]
1. VideoMatte240K 的 fgr 不是很好，去参考 Distinctions646 和 Adobe Image Matting
2. 如果你数据集没有fgr，你就不能训练 fgr
3. true_src 是合成的
4. rec 是不监督的

**Comment by zhanghongyong123456** [comment]
> 感谢大神分享，请教一个很菜的问题，模型输出的3通道的fgr的groud truth是什么呢？
> 
> 我下载数据集VideoMatte240K中的 JPEG SD Format (6GB)，查看fgr目录中的图片，抽样目测其中大部分背景是黑色的，还有少部分是白色的？
> 
> 如果我有数据集用于训练，只包含原始图像和pha(matte)， 那怎么处理得到这个fgr的groud truth呢？
> 
> 另外， VideoMatte240K数据集只有fgr目录与pha目录；训练时，模型输入的true_src图像，是根据pha与另外的背景图像合成的吗？
> 
> 还请教一个问题， 模型输出*rec （r1, r2, r3, r4），训练时是不用监督的吧？即不用groud truth监督训练的吧？ 谢谢

我数据集也是合成图以及alpha，没有单独的前景，我该如何进行训练呢，期待您的回复，代码应该如何进行修改

**Comment by niubiplus2** [comment]
您好，请问您数据集中的pha是怎么获取的呢，自己标注吗？
