### ISSUE TITLE
Add Unity example to README?

### ISSUE THREAD

**Issue by olokobayusuf** [PeterL1n/RobustVideoMatting#36]
Hey there, I just ported RVM to Unity using [NatML](https://github.com/natsuite/NatML), an open-source machine learning runtime. I have questions:

1. Can I make a PR to add a link into the README to a Unity example project demonstrating using RVM?
2. I published the model under my account on NatML Hub. Would you be interested in signing up on Hub, so that I can transfer the model to you?

Here's the model on NatML Hub:

[@natsuite/robust-video-matting](https://hub.natml.ai/@natsuite/robust-video-matting)

**Comment by PeterL1n** [comment]
1. We do accept pull request. There is already a third-party section on README. Both English and Chinese README need to be changed.
2. You can keep it under your account. But please cite our work. You can add a reference back to this GitHub repo.

My bigger concern is license. This repo is under GPT-3. Better have it specified.

**Comment by PeterL1n** [comment]
Also I don't know why is your FPS so low. Did you test it on GPUs? Are you using the ONNX version?

**Comment by olokobayusuf** [comment]
> We do accept pull request. There is already a third-party section on README. Both English and Chinese README need to be changed.

Cool, I'll make a PR soon.

> You can keep it under your account. But please cite our work. You can add a reference back to this GitHub repo.

Yup, there's a link to the project website on Hub. It's the `Model info` link.

> My bigger concern is license. This repo is under GPT-3. Better have it specified.

The Unity package that is linked with the `Get` button has the GPL license included. The NatML package is licensed under GPL, same as the model.

> Also I don't know why is your FPS so low. Did you test it on GPUs? Are you using the ONNX version?

Yup it's using the ONNX version. The benchmarks are from the following devices:

- Samsung Galaxy S21 running with the NNAPI
- iPhone 12 Pro running with CoreML (Apple Neural Engine)
- MacBook Pro 2020 with 2GHz quad-core i5 (no Neural Engine)
- Surface Book tablet running with DirectML

We aren't using high-end GPU's because NatML is currently targeted towards mobile ML.

**Comment by olokobayusuf** [comment]
@PeterL1n made a PR: #56

**Comment by olokobayusuf** [comment]
Merged. Thanks @PeterL1n 🙏

**Comment by mgstar1021** [comment]
@olokobayusuf Can you convert a inpaint model for mobile version using NatML? https://github.com/saic-mdal/lama

**Comment by olokobayusuf** [comment]
@mgstar1021 we'll be able to support models like this early next year.
