### ISSUE TITLE
用自己的数据集finetune，也需要输入背景图片吗？

### ISSUE THREAD

**Issue by dpcq** [PeterL1n/RobustVideoMatting#38]

**Comment by PeterL1n** [comment]
不确定我理解你的问题。

1. 如果你的数据集只有Alpha和Foreground，当然需要将他们合成到背景图片上做训练。
2. 这个模型在跑时是不需要额外背景图，不像BGMv2。

**Comment by pxEkin** [comment]
> 不确定我理解你的问题。
> 
> 1. 如果你的数据集只有Alpha和Foreground，当然需要将他们合成到背景图片上做训练。
> 2. 这个模型在跑时是不需要额外背景图，不像BGMv2。

大佬，我看数据增强有很多方式，如flip\noise\blur等等，能否加rotate-90旋转？？不知道对训练结果影响大不，因为模型输入一般都是720p/1080p的分辨率(1920x1080)， 但是实际场景中也有很多诸如1080x1920 / 720x1080等等，这种分辨率处理感觉效果不是很好啊！！！  我将1080x1920旋转90度成为1920x1080，但是视频里面的人物也倒了90度，所以效果同样不太好，所以想数据增强里面加一下类似增强处理，你觉得可行吗

**Comment by PeterL1n** [comment]
@ToBigboss 我们在训练的时候已经用了随机比例，也包括了竖向的。但你也可以单独再训练。

**Comment by pxEkin** [comment]
> @ToBigboss 我们在训练的时候已经用了随机比例，也包括了竖向的。但你也可以单独再训练。

好的  多谢大佬
