### ISSUE TITLE
新手问题的关于模型结果

### ISSUE THREAD

**Issue by yinjia823** [PeterL1n/RobustVideoMatting#41]
大神辛苦,两个问题请教.......
1.除了更改downsample_ratio的参数值来修正抠图的精度,还可以更改那些参数来更改实现效果?
2.此项目对显卡的要求是否更高?显卡的型号会影响最后结果么?
目前,有执行model的项目,但是效果并不是很理想,再次感谢!

Hello, two questions to consult.......

1. In addition to changing the parameter value of downsample_ratio to correct the accuracy of matting, which other parameters can be changed to change the implementation effect?

2. Does this project have higher requirements for graphics cards? Does the type of graphics card affect the final results?

I have my own project to implement model, but the effect is not very ideal, thank you!(Translation from Youdao Translation)

**Comment by PeterL1n** [comment]
1. That's the only hyperparameter.
2. GPU won't affect the quality, only inference speed.

**Comment by yinjia823** [comment]
> 1. That's the only hyperparameter.
> 2. GPU won't affect the quality, only inference speed.

thanks！
谢谢！

所以视频的原始质量会导致抠图是否干净对吗？
So the original quality of the video will cause the cutout to be clean? right?

另外rvm_mobilenetv3.pth与rvm_resnet50.pth两个模型有什么地方不一样呢？
In addition, what is the difference between rvm_mobilenetv3.pth and rvm_resnet50.pth?

最后，如何才能抠出干净的视频元素呢？
Finally, how can we cut out clean video elements?
（Translation from Google online）

**Comment by PeterL1n** [comment]
1. Make sure your videos have simple backgrounds.
2. ResNet50 uses a different encoder backbone. It is much larger. It supposes to have better quality, but a slower inference speed.

**Comment by yinjia823** [comment]
ok  thanks
try again……
