### ISSUE TITLE
video matting转换成image matting

### ISSUE THREAD

**Issue by PearlDzzz** [PeterL1n/RobustVideoMatting#43]
Hi，一种比较极致的情况，只做image matting的时候：
1、test时，相当于rec=[None]*4保持不变，对matting结果影响大吗？
2、在训练的时候，尤其是stage4，训练数据是imagematte，但seq_length不为1，是把一幅图repeat seq_length倍，作为T个slice，送入网络进行训练的吗？还是怎样？
3、整个训练阶段，能否把seq_length固定为1，由video退化成one image？

**Comment by PeterL1n** [comment]
1. 论文里有图表，对视频影响挺大。
2. 详细见论文，图片送入多帧，并且做 Motion Augmentation，模拟移动，颜色，变焦等变化。
3. 模型是为视频设计的，如果只是图片，你不需要 ConvGRU 层，不推荐使用这个架构。

**Comment by tengshaofeng** [comment]
@PearlDzzz 你用seq_length为1训练抠图了吗，还是用了其他架构
