### ISSUE TITLE
How to customize the background image

### ISSUE THREAD

**Issue by jackhanyuan** [PeterL1n/RobustVideoMatting#44]
I want to change the green background to my own background image. How can I achieve it？

**Comment by PeterL1n** [comment]
If you like GUI, you can use After Effects. Providing the alpha and foreground output, drag them in and use the alpha layer as a brightness matte.

Or you can program it in python.

**Comment by NalinMahajan** [comment]
I want to work on this bug

**Comment by PeterL1n** [comment]
It is not a bug. It is intentionally left out of the demo inference script. We want to keep it simple and people can modify it themselves. The demo script isn't meant to provide all the functionalities.

It becomes complicated when the target background image is not the same size as the video, do we resize by stretching, cropping, etc? What if people want the background to be a video instead. What if the background video and the foreground video have different frame rates? Some may even want the video to start at a certain timestamp, etc.

Someone can build a GUI app for this in a separate repo. I prefer not to add all these into the demo script as it is not part of the research.

**Comment by jackhanyuan** [comment]
I solve this problem, and add the `output-background` option in [inference.py](https://github.com/jackhanyuan/RobustVideoMatting/blob/master/inference.py).

 I also build [a real-time video matting demo](https://github.com/jackhanyuan/RobustVideoMatting/blob/master/inference_camera.py) reference from [BackgroundMattingV2](https://github.com/PeterL1n/BackgroundMattingV2/blob/master/inference_webcam.py), you can customize your image for background.

**Comment by akashAD98** [comment]
@PeterL1n @jackhanyuan its possible to add .mp4 or .gif file as background in video?
