### ISSUE TITLE
VideoMatte240K-HD

### ISSUE THREAD

**Issue by FengMu1995** [PeterL1n/RobustVideoMatting#54]
if I'm going to train stage3 and stage4, the VideoMatte-HD data will be used.  And is it right to modify the following path？VideoMatte240K_JPEG_SD to VideoMatte240K_JPEG_HD
 
 'videomatte': {
        'train': '../matting-data/VideoMatte240K_JPEG_SD/train',
        'valid': '../matting-data/VideoMatte240K_JPEG_SD/valid',
    },

**Comment by PeterL1n** [comment]
Correct

**Comment by niujindacidian** [comment]
您好，有个问题想请问下，stage3是否只训练高分辨率VideoMatte240K_JPEG_HD图像？低分辨率VideoMatte240K_JPEG_SD数据集参与stage3的训练了吗？

stage3中，路径设置如下的话，低分辨率还需要传入吗？
'videomatte': {
'train': '../matting-data/VideoMatte240K_JPEG_HD/train',
'valid': '../matting-data/VideoMatte240K_JPEG_HD/valid',
},
麻烦您了，谢谢！

**Comment by FengMu1995** [comment]
stage3只训练VideoMatte240K_JPEG_HD，

**Comment by niujindacidian** [comment]
train.py  低分辨这里也执行了，有什么作用呢？
# Matting datasets:
        if self.args.dataset == 'videomatte':
            self.dataset_lr_train = VideoMatteDataset(
                videomatte_dir=DATA_PATHS['videomatte']['train'],
                background_image_dir=DATA_PATHS['background_images']['train'],
                background_video_dir=DATA_PATHS['background_videos']['train'],
                size=self.args.resolution_lr,
                seq_length=self.args.seq_length_lr,
                seq_sampler=TrainFrameSampler(),
                transform=VideoMatteTrainAugmentation(size_lr))

**Comment by PeterL1n** [comment]
stage3也需要低分辨率的pass，低分辨率多幀+高分辨率少幀。

**Comment by FengMu1995** [comment]
stage3用的数据集只有hd没有sd吧，然后在lr阶段降采样到512*256，在hr阶段用2048*1024，都是通过HD数据集得到的吧

**Comment by delve-wang** [comment]
> stage3用的数据集只有hd没有sd吧，然后在lr阶段降采样到512_256，在hr阶段用2048_1024，都是通过HD数据集得到的吧

请问stage3和4的训练的低分辨率图片是通过HD数据集得到的，还是要自己设一个新的低分辨率图片的路径？

**Comment by BowenXu2020** [comment]
So for videomatte, we can set **HD** path for all the 1~4 stages, because in stages 1&2, it will be downsized to no larger than 512x512, is my understanding correct?
