### ISSUE TITLE
How long does it take you to train the model on 4 v100？ 

### ISSUE THREAD

**Issue by FengMu1995** [PeterL1n/RobustVideoMatting#55]

**Comment by PeterL1n** [comment]
See paper supplementary section **C. Training**

**Comment by niujindacidian** [comment]
请问stage1,2,3,4 ,num_workers都设了8吗？

**Comment by ArtemSivtsov** [comment]
Our network is trained using 4 Nvidia V100 32G GPUs.
We use mixed precision training [25] to reduce the GPU
memory consumption. The training takes approximately
18, 2, 8, and 14 hours in each stage respectively.

@FengMu1995  it is from Supplementary section :)
