### ISSUE TITLE
[Background Videos Dataset] Train / Val explanation 

### ISSUE THREAD

**Issue by PeppeSaccardi** [PeterL1n/RobustVideoMatting#58]
Hello, can I ask what's going on here:

https://github.com/PeterL1n/RobustVideoMatting/blob/8451b88f4f52dcda2516af2f380265a06de68f79/train_config.py#L48
https://github.com/PeterL1n/RobustVideoMatting/blob/8451b88f4f52dcda2516af2f380265a06de68f79/train_config.py#L50
Are you actually using the train examples also as validation dataset?

**Comment by PeterL1n** [comment]
Fixed. You suppose to pick some clips out as valid.

**Comment by PeppeSaccardi** [comment]
Great, thank you
