### ISSUE TITLE
composite image has a pink edge around the human

### ISSUE THREAD

**Issue by pango99** [PeterL1n/RobustVideoMatting#6]
Hi, I do a test to below image,  I found there is a pink edge around the human on composite and fbr image, I noticed that the beauty in the image was standing in front of blue screen,so whether the pink edge related to this ? 

this is the command I used to do the test:
 python inference.py --variant resnet50 --checkpoint ../Pretrained/rvm_resnet50.pth  --device cpu --input-source n:/AIImage/test --downsample-ratio 0.25 --output-composition ./output/comp --output-alpha ./output/alpha --output-foreground ./output/fore --output-type png_sequence

**Comment by PeterL1n** [comment]
The model probably didn't get trained to work on this uncommon color combinations...
