### ISSUE TITLE
Error on images

### ISSUE THREAD

**Issue by filthy11111** [PeterL1n/RobustVideoMatting#61]
Hi

Running the code perfectly on videos, but when I try run the below on images i get an error.

**Code:**
python inference.py --variant mobilenetv3 --checkpoint ./model/PyTorch/rvm_mobilenetv3.pth --device cuda --input-source ./inputimg --output-type png_sequence --output-composition  ./outputimg --output-video-mbps None --seq-chunk 1

**Error:**
inference.py: error: argument --output-video-mbps: invalid int value: 'None'

Am i missing something? running on Windows via Anacoda

Thanks!

**Comment by PeterL1n** [comment]
Fixed the `inference.py`. Try pull it.

Also, just leave out the --output-video-mbps argument when inference png_sequence output.

**Comment by filthy11111** [comment]
Thanks works perfectly now.
