### ISSUE TITLE
augmentation.py _motion_affine function shear parameters has problems?

### ISSUE THREAD

**Issue by chenying99** [PeterL1n/RobustVideoMatting#63]
augmentation.py   _motion_affine function:

line in 114  115 116 117:

config = dict(degrees=(-10, 10), translate=(0.1, 0.1),
                      scale_ranges=(0.9, 1.1), shears=(-5, 5), img_size=imgs[0][0].size)
angleA, (transXA, transYA), scaleA, (shearXA, shearYA) = transforms.RandomAffine.get_params(**config)

angleB, (transXB, transYB), scaleB, (shearXB, shearYB) = transforms.RandomAffine.get_params(**config)

I track the function transforms.RandomAffine.get_params(**config):

pytorch transforms.py  the  get_params function(line in 1420--1426)：  

shear_x = shear_y = 0.0
if shears is not None:
    shear_x = float(torch.empty(1).uniform_(shears[0], shears[1]).item())
    if len(shears) == 4:
        shear_y = float(torch.empty(1).uniform_(shears[2], shears[3]).item())

shear = (shear_x, shear_y)

if shears=(-5, 5)， then in (shearXA, shearYA)、  (shearXB, shearYB) ,  shearYA 、 shearYB =0.0 

shears=(-5, 5) should be shears=(-5, 5, -5, 5)  ?

 shearYA 、 shearYB =0.0 
augmentation.py  line 128：
shearY = lerp(shearYA, shearYB, percentage)
shearY = 0   ?

I debug this function, print('shearYA:', shearYA, 'shearYB:', shearYB)
print result:  shearYA: 0.0 shearYB: 0.0

**Comment by PeterL1n** [comment]
Are you using the latest torchvision? If so, report the bug to torchvision instead.

**Comment by chenying99** [comment]
yes,   it's  the latest torchvision

shear_x = shear_y = 0.0  the default value is zero

https://github.com/pytorch/vision/blob/main/torchvision/transforms/transforms.py#L1434

if the lenth of shears parameter is equal to 4， it will override shear_x and shear_y's  default value (zero)

**Comment by PeterL1n** [comment]
Yeah, that worth an issue for torchvision.
