### ISSUE TITLE
如何根据 二维mask图片 只提取某个人 , 而不是所有人

### ISSUE THREAD

**Issue by 565ee** [PeterL1n/RobustVideoMatting#66]
![1](https://user-images.githubusercontent.com/28084126/136429740-fc279050-303b-4670-bae0-03bdec11759e.png)
![2](https://user-images.githubusercontent.com/28084126/136429752-8e3e6865-3dd2-42e7-b3d4-dd7b73d1d079.jpg)
如上图  如果只想提取左边 白色mask代表的那个人  如何处理?

**Comment by PeterL1n** [comment]
可以找其他做Video Object Segmentation的模型，一般第一帧提供mask，模型之后会只选择mask的object。

**Comment by 565ee** [comment]
非常感谢 !!!

**Comment by datar001** [comment]
请问这个问题你已经解决了吗？想问下具体的解决方案复现一下，我这边也是2个目标人只需扣1个。感谢！
