### ISSUE TITLE
前景预测

### ISSUE THREAD

**Issue by lyc6749** [PeterL1n/RobustVideoMatting#67]
请问在训练阶段，有遇到第一阶段前景预测图整体偏红或者偏绿的情况吗？有什么解决办法吗？

**Comment by PeterL1n** [comment]
没有遇到，也不应该遇到

**Comment by PearlDzzz** [comment]
> 请问在训练阶段，有遇到第一阶段前景预测图整体偏红或者偏绿的情况吗？有什么解决办法吗？

遇到了和你一样的情况。请问，解决了吗？

**Comment by PeterL1n** [comment]
你能截图吗？

**Comment by lyc6749** [comment]
> 你能截图吗？
![Screenshot from 2021-10-12 13-27-41](https://user-images.githubusercontent.com/33708958/136896939-2a6f1bc7-5f7a-49b4-8897-9e6a5c4db1b2.png)
类似于这个图 第二列是预测的前景，第三列是apha，四列是分割结果

**Comment by PeterL1n** [comment]
不知道，你得自己Debug。

**Comment by decajcd** [comment]
> > 你能截图吗？
> > ![Screenshot from 2021-10-12 13-27-41](https://user-images.githubusercontent.com/33708958/136896939-2a6f1bc7-5f7a-49b4-8897-9e6a5c4db1b2.png)
> > 类似于这个图 第二列是预测的前景，第三列是apha，四列是分割结果

请问你解决了吗，我也是这样的，前景颜色不对。而且用原模型输出前景也不对

**Comment by PeterL1n** [comment]
我怀疑你是不是用opencv之类的软件 没有吧RGB-BGR间正确的转换

**Comment by FengMu1995** [comment]
> 请问在训练阶段，有遇到第一阶段前景预测图整体偏红或者偏绿的情况吗？有什么解决办法吗？

我也遇到了相同的情况，但是没你那个分割得好，问下你的参数和论文里设置得一致吗？

**Comment by PeterL1n** [comment]
修复了一个train.py的bug，应该和这个有关
https://github.com/PeterL1n/RobustVideoMatting/issues/100

**Comment by FengMu1995** [comment]
ok，thanks
