### ISSUE TITLE
background image dataset

### ISSUE THREAD

**Issue by FengMu1995** [PeterL1n/RobustVideoMatting#70]
Could you send me background images for Academic use

**Comment by PeterL1n** [comment]
No, the images are crawled without a license, so I prefer not to send them out. You should be able to crawl your own images fairly easily. The exact keywords for crawling we used are in the BGMv2 paper supplementary. We also run YOLO 5 to remove images with humans in them.

**Comment by FengMu1995** [comment]
OK,THANKS
