### ISSUE TITLE
youtubevis.py initialize YouTubeVISDataset has problems?

### ISSUE THREAD

**Issue by chenying99** [PeterL1n/RobustVideoMatting#73]
youtubevis.py
in line 41:

https://github.com/PeterL1n/RobustVideoMatting/blob/master/dataset/youtubevis.py#L41

self.videos[video_id]) is a dict, not a list,  like as follows:

{'license': 1, 'coco_url': '', 'height': 720, 'width': 1280, 'length': 36, 'date_captured': '2019-04-11 00:55:41.903902', 'file_names': ['01c4cb5ffe/00000.jpg', '01c4cb5ffe/00005.jpg', '01c4cb5ffe/00010.jpg'], 'flickr_url': '', 'id': 11}

len(self.videos[video_id]) is equal to 9， the number of the dict's keys

should be  len(self.videos[video_id]['file_names']) ?

**Comment by luuil** [comment]
Indeed，it is a bug. Others also encountered this problem too.
 #129

**Comment by PeterL1n** [comment]
Fixed.
