### ISSUE TITLE
[Advice] Training in a Low RAM System

### ISSUE THREAD

**Issue by SamHSlva** [PeterL1n/RobustVideoMatting#78]
I am re-training this code in a 64GB RAM system. Do you have any recommendation on how to reduce the memory utilization? I've already reduced T to 4, but still a lot of swap memory usage, which is bottlenecking my training process.

**Comment by PeterL1n** [comment]
No advice. You need to hack yourself.

**Comment by SamHSlva** [comment]
No worries. Thank you again for releasing the code. 
For those with the same struggle, I've reduced the number of workers/GPU from 8 to 3, and I was able to train stage 1, in a 64gb RAM machine. 
I will close the issue.
