### ISSUE TITLE
预测的前景图为啥有背景存在呢

### ISSUE THREAD

**Issue by hust-kevin** [PeterL1n/RobustVideoMatting#79]
训练集中的前景图片只包含人体，为啥预测的前景图会是这么奇怪的呢
![image](https://user-images.githubusercontent.com/23699630/137106055-d9972074-970c-45bb-9560-7b3bbb7eb844.png)
![image](https://user-images.githubusercontent.com/23699630/137106155-f342a0f8-1928-40cc-bc40-1b3df584192e.png)

**Comment by PeterL1n** [comment]
前景的 Loss 只涵盖 alpha > 0 的区域，也就是说当模型输出 alpha = 0 时，前景可以是任意值。你不用在意这些前景区域，因为当和 alpha 做合成时，它不会被显示。

**Comment by hust-kevin** [comment]
@PeterL1n 我在训练好第三个stage的时候，预测的alpha结果是左图这样的，但是当我训练完第四个stage的时候，结果是右图这样的，预测多出了很多轮廓边缘，请问这可能是什么原因导致的呢
![image](https://user-images.githubusercontent.com/23699630/137246614-3510af92-39f7-47a7-9a64-57fa2a9a03cc.png)

**Comment by FengMu1995** [comment]
你解决了吗，我也遇到这个问题

**Comment by liushuailxx** [comment]
同问
