### ISSUE TITLE
colab stuck with no progress

### ISSUE THREAD

**Issue by iperov** [PeterL1n/RobustVideoMatting#8]
9 min, no progress
![2021-08-30_14-14-14](https://user-images.githubusercontent.com/8076202/131324247-14bbe94d-b56d-469c-ae64-b90f4fd6c940.png)

**Comment by PeterL1n** [comment]
If the demo video works and your video doesn't, likely it has something to do with your video's encoding not being recognized. Maybe try encode it to another format or write your own inference script.

**Comment by iperov** [comment]
my video has no sound and it is recognized in ffmpeg. So it is your problem.
Anyway I checked onnx resnet model, and the result is not acceptable for my app.


https://user-images.githubusercontent.com/8076202/131367230-2c88a798-1ad2-4d9a-af21-efde42622535.mp4
