### ISSUE TITLE
关于训练其他物体抠像模型，对于制作训练数据集该修改那些数据集

### ISSUE THREAD

**Issue by zhanghongyong123456** [PeterL1n/RobustVideoMatting#81]
您好，假如我想训练其他物体抠像模型，而非人的抠像模型，对于数据集的制作需要更改那些，因为有太多数据集参与训练，不太明白具体哪一个数据集控制哪一个属性。
![1IV5LI$1E9`NES`K_C E1C3](https://user-images.githubusercontent.com/48466610/137458013-1e90c047-00e1-44d8-bd7b-cee5073e4eba.png)

![image](https://user-images.githubusercontent.com/48466610/137457970-fe135265-71af-4e81-ab8c-f498d71d5a5c.png)

![01](https://user-images.githubusercontent.com/48466610/137460147-8266d967-57ad-4dc7-984b-83e4aaf51386.png)

请问，我这样的分析对吗，期待您的回复

**Comment by PeterL1n** [comment]
如果你要训练抠像猫，COCO 和 YouTubeVIS 我不知道有没有猫的Segmentation Mask，如果有，你需要该程序用猫的类，不然也要换。

**Comment by zhanghongyong123456** [comment]
> 如果你要训练抠像猫，COCO 和 YouTubeVIS 我不知道有没有猫的Segmentation Mask，如果有，你需要该程序用猫的类，不然也要换。

是的，我刚才仔细读了你的论文，里面有介绍使用了COCO以及YouTubeVIS数据集中特定的人的分割，我刚开始看训练文档，里面介绍说是直接下载coco以及YouTubeVIS数据集，以为是可以直接使用的无需进行筛选，对于人的类别分割是在训练代码里面进行分类判断的对吗

**Comment by rover5056** [comment]
> 您好，我有个问题，这个项目对于绿幕视频，效果会不会更惊艳，我想拿绿幕试试

我试用了针对绿幕的视频。感觉还是有需要提升，边缘的绿色还是挺明显的~ 感觉是不是需要针对绿幕单独调整训练集？
可以一起交流

**Comment by zhanghongyong123456** [comment]
> > 您好，我有个问题，这个项目对于绿幕视频，效果会不会更惊艳，我想拿绿幕试试
> 
> 我试用了针对绿幕的视频。感觉还是有需要提升，边缘的绿色还是挺明显的~ 感觉是不是需要针对绿幕单独调整训练集？ 可以一起交流

好的，我加你qq了
