### ISSUE TITLE
CoreML Model outputting nil 

### ISSUE THREAD

**Issue by vade** [PeterL1n/RobustVideoMatting#9]
Hello

Firstly, thank you for this work. Its really fantastic stuff. Bravo!

Now, on to the bad news ha :)

I have been experimenting with the CoreML Model supplied - specifically `rvm_mobilenetv3_1920x1080_s0_25_fp16.mlmodel` - and am unable to get working output 

I am able to initialize the model, create an input, pass a BGRA 32 1920x1080 CVPixelBuffer along with freshly initialized MLMultiArrays properly sized to the inputs. 

I call predict, but I get nil output.

My code:

```
                     let r1i = try MLMultiArray.init(shape: [1, 16, 135, 240], dataType: .float32)
                    let r2i = try MLMultiArray.init(shape: [1, 20, 68, 120], dataType: .float32)
                    let r3i = try MLMultiArray.init(shape: [1, 40, 34, 60], dataType: .float32)
                    let r4i = try MLMultiArray.init(shape: [1, 64, 17, 30], dataType: .float32)
                                        
                    let zeroInput = rvm_mobilenetv3_1920x1080_s0_25_fp16Input.init(src: pixelBuffer, r1i: r1i, r2i: r2i, r3i: r3i, r4i: r4i)
                    
                    let output = try? self.maskModel.prediction(input: zeroInput)
                    
                    Swift.print(output?.fgr)
```

To verify my inputs and models are correct, I set a breakpoint on the print statement, and can introspect variables / view my images in Codes quicklook. See below for debugger output:

Has this model been verified functional?  I am running on macOS 11.5.2, on an Intel Mac with a Vega 20 GPU.

Thank you again for your work and for sharing it!

```
(lldb) po output
nil

(lldb) po self.maskModel
▿ Optional<rvm_mobilenetv3_1920x1080_s0_25_fp16>
  ▿ some : <rvm_mobilenetv3_1920x1080_s0_25_fp16: 0x600002603280>
  
(lldb) po zeroInput
<rvm_mobilenetv3_1920x1080_s0_25_fp16Input: 0x600003c3fa40>

(lldb) po r1i
Float32 1 × 16 × 135 × 240 array

(lldb) po r2i
Float32 1 × 20 × 68 × 120 array

(lldb) po r3i
Float32 1 × 40 × 34 × 60 array

(lldb) po r4i
Float32 1 × 64 × 17 × 30 array

 (lldb) po pixelBuffer
<CVPixelBuffer 0x600001712620 width=1920 height=1080 bytesPerRow=7680 pixelFormat=BGRA iosurface=0x600002434670 poolName=decode attributes={
    PixelFormatDescription =     {
        BitsPerBlock = 32;
        BitsPerComponent = 8;
        BlackBlock = {length = 4, bytes = 0x000000ff};
        CGBitmapContextCompatibility = 1;
        CGBitmapInfo = 8196;
        CGImageCompatibility = 1;
        ComponentRange = FullRange;
        ContainsAlpha = 1;
        ContainsGrayscale = 0;
        ContainsRGB = 1;
        ContainsYCbCr = 0;
        FillExtendedPixelsCallback = {length = 24, bytes = 0x0000000000000000005c4627ff7f00000000000000000000};
        IOSurfaceCoreAnimationCompatibility = 1;
        IOSurfaceOpenGLFBOCompatibility = 1;
        IOSurfaceOpenGLTextureCompatibility = 1;
        OpenGLCompatibility = 1;
        OpenGLFormat = 32993;
        OpenGLInternalFormat = 32856;
        OpenGLTextureCacheCompatibility = 1;
        OpenGLType = 33639;
        PixelFormat = 1111970369;
    };
} propagatedAttachments={
    CGColorSpace = "<CGColorSpace 0x60000024cc00> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; HDTV)";
    CVFieldCount = 1;
    CVImageBufferColorPrimaries = "ITU_R_709_2";
    CVImageBufferTransferFunction = "ITU_R_709_2";
    CVImageBufferYCbCrMatrix = "ITU_R_709_2";
    CVPixelAspectRatio =     {
        HorizontalSpacing = 1;
        VerticalSpacing = 1;
    };
    QTMovieTime =     {
        TimeScale = 24000;
        TimeValue = 0;
    };
} nonPropagatedAttachments={
}>
  
```

**Comment by PeterL1n** [comment]
I have only tested the model on Python using `coremltools`. You can see the exact code in inference doc to reproduce it. Since the python code calls CoreML behind the scene, so I would say the model should be able to run correctly using CoreML engine.

I have not tested it in Swift or Objective-C environment yet. Not exactly sure what is wrong with your code here.

I believe the recurrent inputs are set to be optional. So for the first frame, you should be able to pass in nil for `rXi` inputs and CoreML should internally creates the states. Of course, this is equivalent of you passing in zero-tensor of the correct size. But your recurrent states are FP32. Not sure about that. Maybe best to leave it out for the model to create.

Maybe something is wrong with pixelBuffer? Can you try other input types?

It is weird the output is nil.

**Comment by vade** [comment]
I think you are correct. I was not passing nil, but manually initializing a MLMultiArray. It *appears* that the multi array does not initialize with zero tensors.

Manually forcing memory to 0 seems to have fixed the issue. Thank you!

**Comment by PeterL1n** [comment]
Hum. So the model now works correctly now?

It's weird that even if the initial hidden states are not zeros, it still should not output nil...

If it works, how's the performance in terms of speed?
Also, I think the recurrent states are returned as MLMultiArray, which moves the data back to CPU right? I am not familiar if there is a way for the tensor to stay on GPU. If you figure that out also let me know...

**Comment by vade** [comment]
Yes, it appears to be functioning :) Thank you.

The default initial state with an 'initialized' MLMultiArray (not nil) appears to do weird things. I tried nil as well, and that did not appear to function. Passing a MLMultiArray and initializing memory via something like:

```
func setZero(array:MLMultiArray)
    {
        array.dataPointer.initializeMemory(as: Float32.self, repeating: 0.0, count:  array.count)
    }
```

and then

```
                    var r1i:MLMultiArray? = nil
                    var r2i:MLMultiArray? = nil
                    var r3i:MLMultiArray? = nil
                    var r4i:MLMultiArray? = nil
                    var zeroInput:rvm_mobilenetv3_1920x1080_s0_25_fp16Input? = nil
                    
                    if let r1o = self.recurrentR1o , let r2o = self.recurrentR2o, let r3o = self.recurrentR3o, let r4o = self.recurrentR4o
                    {
                        Swift.print("Have Reccurent Input")
                        zeroInput = rvm_mobilenetv3_1920x1080_s0_25_fp16Input.init(src: pixelBuffer, r1i: r1o, r2i: r2o, r3i: r3o, r4i: r4o)

                    }
                    else
                    {
                        r1i = try MLMultiArray.init(shape: [1, 16, 135, 240], dataType: .float32)
                        self.setZero(array: r1i!)
                        r2i = try MLMultiArray.init(shape: [1, 20, 68, 120], dataType: .float32)
                        self.setZero(array: r2i!)
                        r3i = try MLMultiArray.init(shape: [1, 40, 34, 60], dataType: .float32)
                        self.setZero(array: r3i!)
                        r4i = try MLMultiArray.init(shape: [1, 64, 17, 30], dataType: .float32)
                        self.setZero(array: r4i!)
                        zeroInput = rvm_mobilenetv3_1920x1080_s0_25_fp16Input.init(src: pixelBuffer, r1i: r1i, r2i: r2i, r3i: r3i, r4i: r4i)
                    }
```

where `self.recurrentR1o` and friends are the saved recurrent MLMultiArray outputs from the previous pass.

I believe that MLMultiArray is CPU bound, so yes, its unclear to me if those are also cached on GPU automatically. I also think because of move to unified memory on M1 architecture and with the ANE Tensor processor moving memory to GPU is irrelevant save for older Macs.

**Comment by vade** [comment]
Thank you for the prompt help btw :)
