### ISSUE TITLE
Evaluating BGMv2 on VM low resolution data

### ISSUE THREAD

**Issue by vidit98** [PeterL1n/RobustVideoMatting#97]
Hi, I was trying to reproduce metrics of BGMv2 on VM low-resolution dataset but I was getting significantly different metrics. 

1. I used officially release model with [mobilenetv2 backbone](https://drive.google.com/drive/folders/1NmyTItr2jRac0nLoZMeixlcU1myMiYTs)
2. Used the background image of the first frame as input for all the frames as input.
3. I used[ evaluate_lr.py](https://github.com/PeterL1n/RobustVideoMatting/blob/master/evaluation/evaluate_lr.py) for getting the metrics.
 
I got the following metrics
Reported-   &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  MAD:25.19   MSE:19.63   Grad:2.28    Conn:3.26     dtSSD:2.74
From released wts:  MAD:19.57   MSE:13.76   Grad:4.05    Conn:2.40    dtSSD:3.36

Is there anything else that needs to be done when evaluating BGMv2?

**Comment by PeterL1n** [comment]
Did you using `MattingBase` instead of `MattingRefine` from BGMv2? Refiner shouldn't be used for lr.

**Comment by vidit98** [comment]
I got it right using `MattingBase`. Thanks for the help
